import React from "react"
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./provider";
import StoreProvider from "@/components/StoreProvider";



export const metadata: Metadata = {
  title: "Hertel Webagency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
